# OpenRouter - seu LLM na nuvem gratuito
spring.ai.openai.api-key={YOUR_KEY_HERE}
spring.ai.openai.base-url=https://openrouter.ai/api/v1

# PGVector - banco vetorial local
pgvector.host=localhost
pgvector.port=5432
pgvector.database=ragdb
pgvector.user=postgres
pgvector.password=postgres

# Pasta onde ficam seus arquivos
documents.path=ai-rag-basics/src/main/resources/documents
