# OpenRouter - LLM in cloud
spring.ai.openai.api-key={YOUR_KEY}
spring.ai.openai.base-url=https://openrouter.ai/api/v1

# PGVector - local vector database
pgvector.host=localhost
pgvector.port=5432
pgvector.database=ragdb
pgvector.user=postgres
pgvector.password=postgres

# folder where files will be stored
documents.path=ai-rag-basics/src/main/resources/documents
