pipeline {
    agent { label 'agent-01' }

    options {
        timeout(time: 10, unit: 'MINUTES')        // if stuck abort
        buildDiscarder(logRotator(numToKeepStr: '10')) // mantain only 10 builds
        disableConcurrentBuilds()                  // no parallel builds for the same job
    }

    environment {
        VAULT_ADDR     = 'http://vault:8200'
        PROJECT_FOLDER = 'secret-management-basics'
        APP_IMAGE      = 'secrets-app'
        APP_CONTAINER  = 'secrets-app'
        APP_PORT       = '8080'
    }

    stages {
        stage('Build') {
            steps {
                dir("${PROJECT_FOLDER}") {
                    sh 'chmod +x gradlew'
                    sh './gradlew bootJar'
                }
            }
        }

        stage('Deploy') {
            steps {
                // withVault: search secrets in vault by AppRole and inject them as environment variables only inside this block.
                // The plugin takes care of:
                //   - AppRole auth
                //   - token lifecycle (revoke after use)
                //   - automatic masking in logs
                withVault(
                    configuration: [
                        vaultUrl: env.VAULT_ADDR,
                        vaultCredentialId: 'vault-approle', // "Vault App Role" credential type in Jenkins
                        engineVersion: 2
                    ],
                    vaultSecrets: [
                        [
                            path: 'secret/java-secrets-demo',
                            engineVersion: 2,
                            secretValues: [
                                [envVar: 'DB_PASSWORD', vaultKey: 'DB_PASSWORD'],
                                [envVar: 'API_KEY',     vaultKey: 'API_KEY'],
                                [envVar: 'APP_ENV',     vaultKey: 'APP_ENV']
                            ]
                        ]
                    ]
                ) {
                    sh '''
                        docker stop $APP_CONTAINER || true
                        docker rm   $APP_CONTAINER || true

                        docker build -t $APP_IMAGE ./$PROJECT_FOLDER

                        docker run -d \
                          --name $APP_CONTAINER \
                          -p $APP_PORT:8080 \
                          -e DB_PASSWORD="$DB_PASSWORD" \
                          -e API_KEY="$API_KEY" \
                          -e APP_ENV="$APP_ENV" \
                          $APP_IMAGE
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "Deployed! App available on port: ${APP_PORT}."
        }
        failure {
            echo "Failed! Take a look at the logs."
        }
        always {
            cleanWs() // clean agent's workspace after build
        }
    }
}
