pipeline {
    agent {label 'docker-agent'}
    tools { gradle 'gradle-8.6'}
    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning sub-directory of main repository...'
                git branch: 'master', url: 'https://github.com/AugustoKlaic/Java-Series.git'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing...'
                dir('jenkins-basics') {
                    sh 'gradle clean test'
                }
            }
        }

        stage('Build') {
            steps {
                echo 'Building...'
                dir('jenkins-basics') {
                    sh 'gradle clean build -x test '
                }
            }
        }

        stage('Package') {
            steps {
                echo 'Packaging...'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }

    post {
        success {
            echo 'Build and Deploy succeeded!'
        }
        failure {
            echo 'Build or Deploy failed!'
        }
    }
}
