pipeline {
    agent any

    stages {
        stage ('Pre-requisites') {
            steps {
                script {
                    if (!fileExists('/usr/local/bin/gradle')) {
                        sh 'curl -s https://get.sdkman.io | bash'
                        sh 'source ~/.sdkman/bin/sdkman-init.sh && sdk install gradle'
                    }
                }
            }
        }
        stage('Checkout') {
            steps {
                echo 'Cloning sub-directory of main repository...'
                script {
                    git 'https://github.com/AugustoKlaic/Java-Series.git'
                    sh 'git submodule update --init --recursive jenkins-basics'
                }
            }
        }
        stage('Build') {
            steps {
                echo 'Building...'
                sh './gradlew clean build'
            }
        }
    }
}